In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('data/household_power_consumption.txt', sep=';')
df.head()

/tmp/ipykernel_18475/1434270989.py:1: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/household_power_consumption.txt', sep=';')

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [12]:
df = df.drop(columns=['Time', 'Sub_metering_2', 'Sub_metering_3'])
df.head()

,Date,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
0,16/12/2006,4.216,0.418,234.840,18.400,0.000
1,16/12/2006,5.360,0.436,233.630,23.000,0.000
2,16/12/2006,5.374,0.498,233.290,23.000,0.000
3,16/12/2006,5.388,0.502,233.740,23.000,0.000
4,16/12/2006,3.666,0.528,235.680,15.800,0.000

In [31]:
df.index = pd.to_datetime(df.index, format='%d/%m/%Y')
df.index

DatetimeIndex(['2006-12-16', '2006-12-16', '2006-12-16', '2006-12-16',
               '2006-12-16', '2006-12-16', '2006-12-16', '2006-12-16',
               '2006-12-16', '2006-12-16',
               ...
               '2010-11-26', '2010-11-26', '2010-11-26', '2010-11-26',
               '2010-11-26', '2010-11-26', '2010-11-26', '2010-11-26',
               '2010-11-26', '2010-11-26'],
              dtype='datetime64[ns]', name='Date', length=2049280, freq=None)

In [32]:
df.dtypes

Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
dtype: object

In [33]:
def update_types(df): #find the best matching type
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce') # coerce -> nan if can't be converted
    return df

df = update_types(df)
df.dtypes

Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
dtype: object

In [34]:
df.describe() # what's the range of values? Are there any obvious outliers? How many non-null values are there?

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
count,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,1.091615e+00,1.237145e-01,2.408399e+02,4.627759e+00,6.405834e-02
std,1.057294e+00,1.127220e-01,3.239987e+00,4.444396e+00,1.329055e-03
min,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,6.381600e-02
25%,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,6.381600e-02
50%,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,6.381600e-02
75%,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,6.381600e-02
max,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.282400e-02

In [35]:
df = df.dropna()
df.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
count,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,1.091615e+00,1.237145e-01,2.408399e+02,4.627759e+00,6.405834e-02
std,1.057294e+00,1.127220e-01,3.239987e+00,4.444396e+00,1.329055e-03
min,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,6.381600e-02
25%,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,6.381600e-02
50%,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,6.381600e-02
75%,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,6.381600e-02
max,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.282400e-02

In [36]:
df['Sub_metering_1'] = (df['Sub_metering_1'] + 1) * 0.06
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
Date,,,,,
2006-12-16,4.216,0.418,234.84,18.4,0.063829
2006-12-16,5.360,0.436,233.63,23.0,0.063829
2006-12-16,5.374,0.498,233.29,23.0,0.063829
2006-12-16,5.388,0.502,233.74,23.0,0.063829
2006-12-16,3.666,0.528,235.68,15.8,0.063829

In [37]:
# 7 
mask = (df.index >= '2008-12-27') & (df['Voltage'] >= 242)
df_filtered = df[mask]
df_filtered.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
Date,,,,,
2008-12-27,0.996,0.066,244.81,4.0,0.063829
2008-12-27,1.076,0.162,244.78,4.4,0.063829
2008-12-27,1.064,0.172,244.74,4.4,0.063829
2008-12-27,1.070,0.174,245.28,4.4,0.063829
2008-12-27,0.804,0.184,246.30,3.4,0.063829

In [38]:
df.iloc[88888]

Global_active_power        0.254000
Global_reactive_power      0.000000
Voltage                  238.450000
Global_intensity           1.200000
Sub_metering_1             0.063829
Name: 2007-02-16 00:00:00, dtype: float64

In [39]:
df['Global_active_power'].idxmax()

Timestamp('2009-02-22 00:00:00')

In [41]:
df[['Global_active_power', 'Global_reactive_power', 'Voltage']].sort_values(
    by=['Global_active_power', 'Voltage'],
    ascending=[False, True]
)

            Global_active_power  Global_reactive_power  Voltage
Date
2009-02-22               11.122                  0.174   229.78
2007-03-04               10.670                  0.516   230.20
2007-03-04               10.650                  0.500   229.97
2009-02-22               10.536                  0.192   230.24
2008-11-30               10.348                  0.084   231.60
...                         ...                    ...      ...
2008-08-28                0.076                  0.000   234.88
2008-08-28                0.076                  0.000   235.18
2008-08-28                0.076                  0.000   235.40
2008-08-28                0.076                  0.000   235.64
2008-08-12                0.076                  0.000   236.50

[2049280 rows x 3 columns]

In [42]:
daily_avg = df['Global_active_power'].groupby(df.index).mean()
daily_avg.head(10)

Date
2006-12-16    3.053475
2006-12-17    2.354486
2006-12-18    1.530435
2006-12-19    1.157079
2006-12-20    1.545658
2006-12-21    1.193758
2006-12-22    1.625929
2006-12-23    3.314851
2006-12-24    1.770842
2006-12-25    1.904944
Name: Global_active_power, dtype: float64